env:
  browser: true
  es6: true
  node: true

extends:
  - eslint:recommended
  - plugin:react/recommended

parserOptions:
  sourceType: module
  ecmaFeatures:
    jsx: true

plugins:
  - react

root: true

rules:
  react/jsx-uses-react: warn
  react/jsx-uses-vars: warn
  react/no-deprecated: warn # TODO: change to "error"
  react/no-direct-mutation-state: warn # TODO: change to "error"
  react/no-find-dom-node: warn # TODO: change to "error"
  react/prop-types: off # TODO: change to "error"

  comma-dangle: off
  eqeqeq: off # TODO: change to "error"
  no-console: off
  no-unused-vars: [warn, {vars: all, args: none}]
  no-var: off # TODO: change to "error"
  prefer-const: off # TODO: change to "error"
  quotes: [off, double] # TODO: change to "error"
