files:
  include: ./static/**/*.scss

options:
  merge-default-rules: true

rules:
  class-name-format: 0
  force-attribute-nesting: 0
  force-element-nesting: 0
  force-pseudo-nesting: 0
  hex-length: 2
  hex-notation: [2, {style: lowercase}]
  leading-zero: [2, {include: true}]
  no-color-keywords: 2
  no-color-literals: 0
  no-css-comments: 0
  no-ids: 0
  no-important: 1
  no-qualifying-elements: 0
  no-url-protocols: 0
  placeholder-in-extend: 0
  property-sort-order: 0
  quotes: [1, {style: double}]
  single-line-per-selector: 2
  space-after-comma: 2
  url-quotes: 2
  zero-unit: 2
  no-warn: 0
